CODE_VALIDATION_ERROR = "VALIDATION_ERROR"
CODE_HTTP_ERROR = "HTTP_ERROR"
CODE_INTERNAL_ERROR = "INTERNAL_ERROR"

MESSAGE_VALIDATION_ERROR = "Request validation failed."
MESSAGE_INTERNAL_ERROR = "An unexpected error occurred."
